### ISSUE TITLE
Identify stakeholders and create user stories

### ISSUE THREAD

**Issue by Epanastatis2020** [Epanastatis2020/book-a-tutor#2]
Need to identify stakeholders and create appropriate user stories to inform development

**Comment by Epanastatis2020** [comment]
The obvious ones are students and educators... Anything else?

**Comment by galluk** [comment]
Booking a session: each session will require a student, tutor and subject.
So, DB will need a table for users, subjects, tutor_subjects, booking

**Comment by Epanastatis2020** [comment]
AS An educator
I WANT to be able to manage tutoring sessions with students
SO THAT I am better able to manage my time and learning outcomes

**Comment by Epanastatis2020** [comment]
AS A student
I WANT to see when specific tutors are available
I WANT to be able to filter available tutors by subject
SO THAT I can book a tutoring session
